version: '3'
services:
  app:
    build: ./
    image: switchbot-meter-monitor
    ports:
      - ${APP_PORT:-3000}:3000
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    restart: always

  devices:
    profiles: [devices]
    image: node:18-alpine
    env_file:
      - .env
    volumes:
      - ./:/app
    command: sh -c 'cd app && yarn install && node /app/tools/list_devices.js'

  appdev:
    profiles: [appdev]
    image: node:18-alpine
    ports:
      - ${APP_PORT:-3000}:3000
    environment:
      - NODE_ENV=development
    env_file:
      - .env
    volumes:
      - ./:/app
    command: sh -c 'cd app && yarn install && yarn start'